Algoritmo "test1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2021
Var
// Seção de Declarações das variáveis 
 nome: caractere
 idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
nome <- "Pedro Wilian"
idade <- 12

escreva(nome, " tem ", idade, " de idade!")

Fimalgoritmo